name: pytests
on: push

jobs:
  build:
    name: Run pytest
    if: "contains(github.event.head_commit.message, 'pytest')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setting Up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest delta-dx
      - name: Run tests with pytest
        run: pytest
